Add tr
msasikanth/twine pull request #386
Opened 2024-03-17 16:40 UTC by mikropsoft

2024-03-27 01:54 UTC, msasikanth commented
@mikropsoft can you please run code formatting once? You can run this Gradle command `gradle spotlessApply`

2024-03-27 01:57 UTC, msasikanth requested changes

2024-03-27 01:57 UTC, msasikanth commented on resources/strings/src/commonMain/kotlin/dev/sasikanth/rss/reader/resources/strings/TrTwineStrings.kt
> +@LyricistStrings(languageTag = Locales.TR, default = true)
Please remove the default value here.

2024-03-27 16:56 UTC, mikropsoft commented on resources/strings/src/commonMain/kotlin/dev/sasikanth/rss/reader/resources/strings/TrTwineStrings.kt
> +@LyricistStrings(languageTag = Locales.TR, default = true)
changed the value to "false"

2024-03-28 01:51 UTC, msasikanth commented
@mikropsoft there are duplicate commits and merge commit. Can you please clean up the PR commits, so that I can merge this in, please?

2024-03-28 05:09 UTC, mikropsoft commented
> @mikropsoft there are duplicate commits and merge commit. Can you please clean up the PR commits, so that I can merge this in, please? 

I don't know exactly how to do this. Do you want me to reopen Pr

2024-03-28 05:19 UTC, msasikanth commented
> > @mikropsoft there are duplicate commits and merge commit. Can you please clean up the PR commits, so that I can merge this in, please?
> 
> I don't know exactly how to do this. Do you want me to reopen Pr

Yes, please.

2024-03-28 05:21 UTC, closed without merging

2024-03-28 05:21 UTC, mikropsoft commented
Sure